# Generated by Django 4.2.3 on 2023-11-17 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('avatar', models.ImageField(blank=True, default='default/avatars/avatar_default.png', upload_to=utils.managers.MediaPath.directory_path_datatime, verbose_name='Фото профиля')),
                ('bio', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, default='default/banners/banner_default.jpg', upload_to=utils.managers.MediaPath.directory_path_datatime)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='accounts.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
