# Generated by Django 4.2.7 on 2023-11-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_avatar_alter_profile_banner'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupChat',
            new_name='Chat',
        ),
    ]
