# Generated by Django 4.2.7 on 2023-11-20 07:52

from django.db import migrations, models
import utils.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_avatar_alter_profile_banner'),
        ('chats', '0003_chat_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(related_name='admin_chats', to='accounts.profile', verbose_name='Администраторы'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=utils.managers.MediaPath.directory_path_datatime),
        ),
    ]
